In [1]:
import torch

### Build in instruments

In [2]:
# we can create Sequential Model like this
model = torch.nn.Sequential(
    torch.nn.Linear(784, 128),
    torch.nn.ReLU(),
    torch.nn.Linear(128, 10)
)

model

Sequential(
  (0): Linear(in_features=784, out_features=128, bias=True)
  (1): ReLU()
  (2): Linear(in_features=128, out_features=10, bias=True)
)

In [3]:
# test our model
input = torch.rand([16, 784], dtype=torch.float32)

out = model(input)
out.shape

torch.Size([16, 10])

In [4]:
# our we can register our layers mannualy
model = torch.nn.Sequential()
model.add_module('layer_1', torch.nn.Linear(784, 128))
model.add_module('ReLU', torch.nn.ReLU())
model.add_module('layer_2', torch.nn.Linear(128, 10))

In [5]:
# test our model
input = torch.rand([16, 784], dtype=torch.float32)

out = model(input)
out.shape

torch.Size([16, 10])

In [6]:
# get model state dictionary
model.state_dict()

OrderedDict([('layer_1.weight',
              tensor([[ 0.0253,  0.0143, -0.0203,  ..., -0.0171, -0.0241,  0.0193],
                      [-0.0234, -0.0106,  0.0014,  ..., -0.0020, -0.0188,  0.0013],
                      [-0.0074,  0.0121, -0.0268,  ...,  0.0354, -0.0289, -0.0101],
                      ...,
                      [ 0.0317,  0.0256, -0.0030,  ..., -0.0293,  0.0112, -0.0202],
                      [-0.0220, -0.0230, -0.0263,  ..., -0.0303, -0.0316,  0.0074],
                      [ 0.0152,  0.0150, -0.0074,  ..., -0.0198,  0.0104,  0.0034]])),
             ('layer_1.bias',
              tensor([ 0.0031, -0.0310,  0.0238,  0.0299,  0.0060, -0.0134,  0.0305,  0.0253,
                      -0.0300,  0.0167,  0.0021, -0.0080,  0.0320, -0.0161,  0.0238,  0.0330,
                      -0.0070, -0.0020,  0.0182,  0.0308, -0.0293,  0.0022, -0.0047,  0.0253,
                       0.0018,  0.0200,  0.0105,  0.0018,  0.0288, -0.0170, -0.0264,  0.0263,
                      -0.032

In [7]:
# get model optimisation parameters(training parameters)
# in this form they usually comes in optimisation algorithm
for parameter in model.parameters():
    print(parameter)
    print(parameter.shape, end='\n\n')

Parameter containing:
tensor([[ 0.0253,  0.0143, -0.0203,  ..., -0.0171, -0.0241,  0.0193],
        [-0.0234, -0.0106,  0.0014,  ..., -0.0020, -0.0188,  0.0013],
        [-0.0074,  0.0121, -0.0268,  ...,  0.0354, -0.0289, -0.0101],
        ...,
        [ 0.0317,  0.0256, -0.0030,  ..., -0.0293,  0.0112, -0.0202],
        [-0.0220, -0.0230, -0.0263,  ..., -0.0303, -0.0316,  0.0074],
        [ 0.0152,  0.0150, -0.0074,  ..., -0.0198,  0.0104,  0.0034]],
       requires_grad=True)
torch.Size([128, 784])

Parameter containing:
tensor([ 0.0031, -0.0310,  0.0238,  0.0299,  0.0060, -0.0134,  0.0305,  0.0253,
        -0.0300,  0.0167,  0.0021, -0.0080,  0.0320, -0.0161,  0.0238,  0.0330,
        -0.0070, -0.0020,  0.0182,  0.0308, -0.0293,  0.0022, -0.0047,  0.0253,
         0.0018,  0.0200,  0.0105,  0.0018,  0.0288, -0.0170, -0.0264,  0.0263,
        -0.0320,  0.0162,  0.0261,  0.0205,  0.0298,  0.0222, -0.0344,  0.0339,
         0.0350, -0.0162, -0.0148, -0.0202, -0.0128, -0.0209, -0.0221, 

In [8]:
# use before training
model.train()
# use before validation and testing
model.eval()

Sequential(
  (layer_1): Linear(in_features=784, out_features=128, bias=True)
  (ReLU): ReLU()
  (layer_2): Linear(in_features=128, out_features=10, bias=True)
)

<ul>Minuses in nn.Sequential
    <li>Can not customize input/output shape</li>
    <li>Can not use layers in our own order</li>
</ul>

### Write down our own model classes

In [9]:
# class with custom input/output
class MyModel(torch.nn.Module):
    def __init__(self, input, output):
        super().__init__()
        # register our layers
        self.layer_1 = torch.nn.Linear(input, 128)
        self.act = torch.nn.ReLU()
        self.layer_2 = torch.nn.Linear(128, output)

    def forward(self, x):
        x = self.layer_1(x)
        x = self.act(x)
        out = self.layer_2(x)
        return out

In [10]:
model = MyModel(784, 10)

In [11]:
# check
input = torch.rand([16, 784], dtype=torch.float32)

out = model(input)
out.shape

torch.Size([16, 10])

#### Multiply input/output

In [12]:
class MyModel(torch.nn.Module):
    def __init__(self, input, output):
        super().__init__()
        self.layer_1 = torch.nn.Linear(input, 128)
        self.act = torch.nn.ReLU()
        self.layer_2 = torch.nn.Linear(128, output)

    def forward(self, x, y):
        x = self.layer_1(x)
        x = self.act(x + y)
        out = self.layer_2(x)
        return out, x

In [13]:
model = MyModel(784, 10)

In [14]:
# check
x = torch.rand([16, 784], dtype=torch.float32)
y = torch.rand([16, 128], dtype=torch.float32)

out = model(x, y)

In [15]:
len(out)

2

In [16]:
out[0].shape

torch.Size([16, 10])

In [17]:
out[1].shape

torch.Size([16, 128])

### Using ModuleList and ModuleDict

In [18]:
class MyModel(torch.nn.Module):
    def __init__(self, input, output, hidden_size=2048, choice='relu'):
        super().__init__()
        # torch.nn.ModuleDict({}) - save module names by keys. Fit for all layers, not only for regularisation.
        self.activasions = torch.nn.ModuleDict({
            'lrelu': torch.nn.LeakyReLU(),
            'relu': torch.nn.ReLU()
        })
        # nn.ModuleList() - need to write forward pass login(unlike of sequential).
        self.layers = torch.nn.ModuleList()
        for i in range(10):
            self.layers.add_module(f'layer_{i}', torch.nn.Linear(input, hidden_size))
            self.layers.add_module(f'act_{i}', self.activasions[choice])
            input = hidden_size
            hidden_size = int(hidden_size // 2)
        self.layers.add_module('layer_out', torch.nn.Linear(input, output))
        

    def forward(self, x):
        outputs = []
        for i, layer in enumerate(self.layers):
            x = layer(x)
            if i != 0 and i % 2 == 0 and i % 4 != 0:
                outputs.append(x)
        outputs.append(x)
        return outputs

In [19]:
model = MyModel(784, 2)
model

MyModel(
  (activasions): ModuleDict(
    (lrelu): LeakyReLU(negative_slope=0.01)
    (relu): ReLU()
  )
  (layers): ModuleList(
    (0): Linear(in_features=784, out_features=2048, bias=True)
    (1): ReLU()
    (2): Linear(in_features=2048, out_features=1024, bias=True)
    (3): ReLU()
    (4): Linear(in_features=1024, out_features=512, bias=True)
    (5): ReLU()
    (6): Linear(in_features=512, out_features=256, bias=True)
    (7): ReLU()
    (8): Linear(in_features=256, out_features=128, bias=True)
    (9): ReLU()
    (10): Linear(in_features=128, out_features=64, bias=True)
    (11): ReLU()
    (12): Linear(in_features=64, out_features=32, bias=True)
    (13): ReLU()
    (14): Linear(in_features=32, out_features=16, bias=True)
    (15): ReLU()
    (16): Linear(in_features=16, out_features=8, bias=True)
    (17): ReLU()
    (18): Linear(in_features=8, out_features=4, bias=True)
    (19): ReLU()
    (20): Linear(in_features=4, out_features=2, bias=True)
  )
)

In [20]:
# check
input = torch.rand([16, 784], dtype=torch.float32)

out = model(input)

In [21]:
len(out)

6